name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Verify Terraform Installation
        run: terraform version

      - name: Install Pre-commit
        run: python -m pip install --upgrade pip pre-commit

      - name: Run Pre-commit Hooks
        run: pre-commit run --show-diff-on-failure --color=always --all-files
